/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:36a1e32a-4d5d-43c7-bc54-0b574fc465e4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ieM9HaXMP",
    "aws_user_pools_web_client_id": "63o7k4726g6k50vth9v4lq9vcj",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rnzezeb4lzfoplx7urrwqncsum.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
